name = "leave-bot-worker"
main = "src/index.js"
compatibility_date = "2023-10-02"

# [vars]
# You can set these in the Cloudflare Dashboard or via `wrangler secret put`
# GOOGLE_PRIVATE_KEY = "..."
# GOOGLE_CLIENT_EMAIL = "..."
# SHEET_ID = "..."
# DRIVE_FOLDER_ID = "..."
# LINE_CHANNEL_ACCESS_TOKEN = "..."
