name = "leave-bot-worker"
main = "src/index.js"
compatibility_date = "2024-12-05"

[triggers]
crons = ["0 1 * * *"] # 1:00 AM UTC = 9:00 AM Taiwan

# [vars]
# SHEET_ID = "..." (Provided in environment)
# You can set these in the Cloudflare Dashboard or via `wrangler secret put`
# GOOGLE_PRIVATE_KEY = "..."
# GOOGLE_CLIENT_EMAIL = "..."
# SHEET_ID = "..."
# DRIVE_FOLDER_ID = "..."
# LINE_CHANNEL_ACCESS_TOKEN = "..."
[vars]
LINE_CHANNEL_ID = "2008645610"

